#!/usr/bin/env bash

# Load configuration
CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$CURRENT_DIR/config"

# Switch to app
COMMAND="cd $LOCAL_PATH"
echo $COMMAND
eval $COMMAND

# Export remote db
COMMAND="ssh $SERVER_USER@$SERVER_DOMAIN 'cd $SERVER_PATH && $WP_CLI_COMMAND db export dump.sql'"
echo $COMMAND
eval $COMMAND

# Copy SQL file from server
COMMAND="scp $SERVER_USER@$SERVER_DOMAIN:$SERVER_PATH/dump.sql dump.sql"
echo $COMMAND
eval $COMMAND

# Import and replace domain
COMMAND="wp db import dump.sql && wp search-replace http://$SERVER_DOMAIN http://$LOCAL_DOMAIN"
echo $COMMAND
eval $COMMAND